site_name: Finch.io help page
theme: null
theme_dir: "theme"
docs_dir: "content"
site_dir: "docs"
ga: "UA-65681916-4"

pages:
   - Home: "index.md"
   - Documentation:
      - Documentation: "documentation.md"
      - Finch desktop:
         - "desktop/index.md"
         - Installation: "desktop/installation.md"
         - Editor: "desktop/editor.md"
         - Shortcuts: "desktop/shortcuts.md"
         - Media queries: "desktop/media-queries.md"
      - Wordpress:
         - "wordpress/index.md"
         - Installation: "wordpress/installation.md"
         - Usage: "wordpress/usage.md"
         - Troubleshooting: "wordpress/troubleshooting.md"
      - Live setup: "live-setup.md"
   - FAQ: "faq.md"
   - Support: "support.md"

markdown_extensions:
    - toc:
        permalink: true
